apiVersion: v1
kind: Service
metadata:
  name: webserver-backend
  labels:
    service: webserver-backend
spec:
  type: ClusterIP
  selector:
    app: webserver-backend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-backend
  labels:
    app: webserver-backend
spec:
  selector:
    matchLabels:
      app: webserver-backend
  template:
    metadata:
      labels:
        app: webserver-backend
    spec:
      serviceAccountName: fastapi
      containers:
        - name: webserver-backend
          image: webserver-backend
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_PASSWORD
              value: postgres123
            - name: POSTGRES_USER
              value: opensoar
            - name: POSTGRES_HOST
              value: 192.168.0.90
            - name: POSTGRES_DB
              value: opensoar
            - name: AUTH_BACKEND_SECRET
              value: OpenSOAR@11042018
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fastapi-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-aggregate-to-admin
subjects:
- kind: ServiceAccount
  name: fastapi
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fastapi-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: fastapi
  namespace: default